**Cell 1: Importing NumPy & Basic Array Creation**

In [1]:
# 1. Importing NumPy and creating basic arrays
import numpy as np

# Creating a 1D Array (vector)
array_1d = np.array([10, 20, 30, 40, 50])

# Creating a 2D Array (matrix)
array_2d = np.array([[1, 2, 3], [4, 5, 6]])

print("--- 1D Array Properties ---")
print("Array:", array_1d)
print("Type:", type(array_1d))
print("Data Type:", array_1d.dtype)
print("Shape:", array_1d.shape)
print("Dimensions:", array_1d.ndim)

print("\n--- 2D Array Properties ---")
print("Matrix:\n", array_2d)
print("Shape:", array_2d.shape)
print("Dimensions:", array_2d.ndim)

--- 1D Array Properties ---
Array: [10 20 30 40 50]
Type: <class 'numpy.ndarray'>
Data Type: int64
Shape: (5,)
Dimensions: 1

--- 2D Array Properties ---
Matrix:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Dimensions: 2


**Cell 2: Specialized Array Initializers**

In [2]:
# 2. Specialized Array Initializers

# Create an array of five zeros
zeros_arr = np.zeros(5)

# Create a 2x3 matrix of ones
ones_mat = np.ones((2, 3))

# Create an array from 0 to 9 (exclusive)
range_arr = np.arange(0, 10, 2) # Start, Stop, Step

# Create 5 evenly spaced values between 0 and 100
linspace_arr = np.linspace(0, 100, 5)

# Create a 2x2 matrix with random floats between 0 and 1
random_mat = np.random.rand(2, 2)

print("Zeros Array:", zeros_arr)
print("Ones Matrix:\n", ones_mat)
print("Arange Array (step 2):", range_arr)
print("Linspace Array:", linspace_arr)
print("Random 2x2 Matrix:\n", random_mat)

Zeros Array: [0. 0. 0. 0. 0.]
Ones Matrix:
 [[1. 1. 1.]
 [1. 1. 1.]]
Arange Array (step 2): [0 2 4 6 8]
Linspace Array: [  0.  25.  50.  75. 100.]
Random 2x2 Matrix:
 [[0.43131747 0.2507058 ]
 [0.18482433 0.38487495]]


**Cell 3: Slicing & Advanced Indexing**

In [3]:
# 3. Slicing and Indexing

# 1D Slicing
numbers = np.array([10, 15, 20, 25, 30, 35, 40])
print("1D Slice (index 1 to 4):", numbers[1:5])

# 2D Indexing & Slicing
matrix = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print("\nFull Matrix:\n", matrix)
print("Element at row 1, col 2:", matrix[1, 2]) # Prints 60 (0-indexed)
print("First row:", matrix[0, :])
print("Last column:", matrix[:, -1])
print("Sub-matrix (top-left 2x2):\n", matrix[0:2, 0:2])

1D Slice (index 1 to 4): [15 20 25 30]

Full Matrix:
 [[10 20 30]
 [40 50 60]
 [70 80 90]]
Element at row 1, col 2: 60
First row: [10 20 30]
Last column: [30 60 90]
Sub-matrix (top-left 2x2):
 [[10 20]
 [40 50]]


**Cell 4: Vectorized Arithmetic Operations**

In [4]:
# 4. Element-wise Vectorized Math

arr_a = np.array([1, 2, 3, 4])
arr_b = np.array([10, 20, 30, 40])

# Operations
addition = arr_a + arr_b
multiplication = arr_a * arr_b
squared = arr_a ** 2

print("Array A:", arr_a)
print("Array B:", arr_b)
print("A + B:", addition)
print("A * B:", multiplication)
print("A squared:", squared)

Array A: [1 2 3 4]
Array B: [10 20 30 40]
A + B: [11 22 33 44]
A * B: [ 10  40  90 160]
A squared: [ 1  4  9 16]


**Cell 5: Statistical & Aggregate Functions**

In [5]:
# 5. Descriptive Statistics & Aggregation

data = np.array([
    [12, 15, 18],
    [20, 22, 25]
])

print("Data Matrix:\n", data)
print("Global Sum:", np.sum(data))
print("Global Mean:", np.mean(data))
print("Standard Deviation:", np.std(data))

# Aggregation along axes
print("Column-wise Sums (Axis 0):", np.sum(data, axis=0))
print("Row-wise Means (Axis 1):", np.mean(data, axis=1))

Data Matrix:
 [[12 15 18]
 [20 22 25]]
Global Sum: 112
Global Mean: 18.666666666666668
Standard Deviation: 4.307615994440028
Column-wise Sums (Axis 0): [32 37 43]
Row-wise Means (Axis 1): [15.         22.33333333]


**Cell 6: Practical Program 1 – Normalized Score Scaler**

In [6]:
# 6. Practical Program 1: Min-Max Feature Scaler

def min_max_scale(scores):
    min_val = np.min(scores)
    max_val = np.max(scores)
    
    # Vectorized normalization formula
    normalized_scores = (scores - min_val) / (max_val - min_val)
    return normalized_scores

# Dummy Raw ML feature scores (e.g., house sizes or test scores)
raw_features = np.array([1200, 1500, 800, 2400, 1800, 950], dtype=float)

scaled_features = min_max_scale(raw_features)

print("--- Min-Max Scaler ---")
print("Raw Features:      ", raw_features)
print("Normalized (0 to 1):", np.round(scaled_features, 4))

--- Min-Max Scaler ---
Raw Features:       [1200. 1500.  800. 2400. 1800.  950.]
Normalized (0 to 1): [0.25   0.4375 0.     1.     0.625  0.0938]


**Cell 7: Practical Program 2 – Store Sales Analysis Matrix**

In [7]:
# 7. Practical Program 2: Multi-Department Sales Analyzer

# Row = Days (Day 1 to 4), Column = Departments (Electronics, Apparel, Groceries)
sales_matrix = np.array([
    [1200, 800, 1500], # Day 1
    [1400, 950, 1600], # Day 2
    [1100, 1200, 1400],# Day 3
    [1700, 1100, 1900] # Day 4
])

# 1. Total revenue generated per department over 4 days (column sum)
dept_totals = np.sum(sales_matrix, axis=0)

# 2. Average total revenue generated per day across all departments (row mean)
daily_means = np.mean(sales_matrix, axis=1)

print("--- Store Sales Performance Analysis ---")
print("Sales Matrix (Days x Depts):\n", sales_matrix)
print("-" * 45)
print("Total Sales per Department:")
print(f"  Electronics: ${dept_totals[0]} | Apparel: ${dept_totals[1]} | Groceries: ${dept_totals[2]}")
print("-" * 45)
print("Average Store Revenue per Day:")
for i, avg_rev in enumerate(daily_means, start=1):
    print(f"  Day {i}: ${avg_rev:.2f}")

--- Store Sales Performance Analysis ---
Sales Matrix (Days x Depts):
 [[1200  800 1500]
 [1400  950 1600]
 [1100 1200 1400]
 [1700 1100 1900]]
---------------------------------------------
Total Sales per Department:
  Electronics: $5400 | Apparel: $4050 | Groceries: $6400
---------------------------------------------
Average Store Revenue per Day:
  Day 1: $1166.67
  Day 2: $1316.67
  Day 3: $1233.33
  Day 4: $1566.67
